### ISSUE TITLE
Jukebox / Music isn't working

### ISSUE THREAD

**Issue by AdrianKoshka** [flathub/org.openttd.OpenTTD#1]
When I open the Jukebox to select music, it just wildly flips through all of the tracks, and plays none of them.

**Comment by ghisvail** [comment]
^ reported upstream.

**Comment by AdrianKoshka** [comment]
Thanks!

**Comment by ghisvail** [comment]
Fluidsynth support has been merged upstream and should be released with version 1.9.0. Hopefully, it will help fix this issue.

**Comment by ghisvail** [comment]
The bug has been reopened upstream. I don't know much about fluidsynth to fix the issue myself.

**Comment by ghisvail** [comment]
This is now fixed with the latest Flatpak release.
