### ISSUE TITLE
Game does not start, only music

### ISSUE THREAD

**Issue by senseiski** [flathub/org.openttd.OpenTTD#103]
With the latest flatpak version of OpenTTD, the game does not start, but the music does.
I've tried to run it from the terminal flatpak run org.openttd.OpenTTD to see if it throws an error but it doesn't.
My system is Linux Mint Cinnamon 21.1 w kernel 5.15.0-67 and flatpak version 1.12.7-1.
Not sure how to provide a more detailed log - when the music starts I can see the OpenTTD process but the game does not start and I have to kill the process in order to get the music to stop.

EDIT: This only happens with latest version from 11/02. I've downgraded to the flatpak released on 06/02 and it works.

**Comment by mu1f407** [comment]
Same issue for me on LMDE 5 (Linux Mint based on Debian 11). Thanks for the hint on downgrade @senseiski. Reverting to release from 06/02 fixes it for me as well.

**Comment by ghisvail** [comment]
I am guessing this is because Linux Mint is X11 only.

**Comment by ghisvail** [comment]
What happens if you override sandox permission to switch to X11 with

```console
flatpak override --socket=fallback-x11 org.openttd.OpenTTD
```

**Comment by mu1f407** [comment]
Well, yesterday I just started the OpenTTD to check. But now I tried to play a game and found the scrolling doesn't work. Behaves exactly like the [Without this patch](https://drive.google.com/file/d/10Vw7ozy04gW-khKoA7aX5TZHJ5lZxDHi/view?usp=sharing) in [this comment](https://github.com/OpenTTD/OpenTTD/pull/10141#issuecomment-1338938824). Looks like some changes are incompatible between Wayland and X11.

**Comment by KenSharp** [comment]
See the abovementioned bug for some proper debugging.

**Comment by ghisvail** [comment]
> See the abovementioned bug for some proper debugging.

What are the conclusions then?

**Comment by H-Sachse** [comment]
The yaml is missing `--socket=fallback-x11` in the `finish-args` section.
Building it like that works for me

**Comment by ghisvail** [comment]
> The yaml is missing `--socket=fallback-x11` in the `finish-args` section. Building it like that works for me

Feel free to use an override or Flatseal 👍

**Comment by H-Sachse** [comment]
Oh come on, really? Just add the line and the issue is solved for all users.

**Comment by KenSharp** [comment]
Probably because it's already fixed.

**Comment by ghisvail** [comment]
> Oh come on, really? Just add the line and the issue is solved for all users using x11.

You're welcome
