### ISSUE TITLE
Would you allow using metainfo by upstream?

### ISSUE THREAD

**Issue by pemensik** [flathub/org.openttd.OpenTTD#123]
I have made PR https://github.com/OpenTTD/OpenTTD/pull/11406, which should add metainfo file into the upstream. They are requesting removing Copyright statement, would you mind doing that? Is there any other issue you would have with using your metainfo as template?

**Comment by ghisvail** [comment]
> add metainfo file into the upstream

Thanks for looking into it. If upstream accepts it *fully*, i.e. which does not require additional patching to pass AppStream validation, then great.

> They are requesting removing Copyright statement, would you mind doing that?

Copyright statements for public domain are useless anyway, so please go ahead.

> Is there any other issue you would have with using your metainfo as template?

I am pretty sure I started from an existing template at the time, but I can't remember where.

**Comment by pemensik** [comment]
Do you validate with strict or relaxed? They do not like maintaining releases history for obvious reasons.

**Comment by ghisvail** [comment]
> Do you validate with strict or relaxed?

So far I was on default which is strict, I guess?

> They do not like maintaining releases history for obvious reasons.

Fair enough. It's a shame since they have all the pieces of information (release history, change log, ...)

**Comment by pemensik** [comment]
Well, if we can provide working infrastructure to fill everything automatically, I expect they would not complain.

**Comment by ghisvail** [comment]
Meanwhile, I queued an [update](https://github.com/flathub/org.openttd.OpenTTD/pull/124) up with your fixes.

**Comment by ghisvail** [comment]
Closing since the proposal has been rejected upstream
