### ISSUE TITLE
wrong license on the flathub page

### ISSUE THREAD

**Issue by auge8472** [flathub/org.openttd.OpenTTD#18]
On the [Flathub page for OpenTTD](https://flathub.org/apps/details/org.openttd.OpenTTD) the specified license is Apache 2.0. The correct [license of OpenTTD is GPL v2](https://github.com/OpenTTD/OpenTTD/blob/master/README.md#30-licensing).

**Comment by ghisvail** [comment]
You are correct. Could you submit your PR to this project instead of your personal fork?

**Comment by ghisvail** [comment]
I found a way to create it. That's a Github feature I was not aware of. It's merged.

Thanks for fixing this silly mistake!

**Comment by auge8472** [comment]
The PR in my own fork was a mistake. Sorry for the confusion.
