### ISSUE TITLE
Beta branch is building a debug build

### ISSUE THREAD

**Issue by TrueBrain** [flathub/org.openttd.OpenTTD#32]
I mentioned this in one of the issues you raised on the OpenTTD repo, but it might got lost, so here an issue to track :)

By default, CMake projects tend to build debug builds; OpenTTD is not an exception. The resulting build is rather slow, as it does all kinds of extra validations. Which, I would guess, is not what you would want for a game on flathub.

My suggestion would be to switch to `RelWithDebInfo`, which is a release build, including debug-information in case a crash happens. This is what we do for our official binaries.

A good example of how to do that can be found here:
https://github.com/flathub/io.openrct2.OpenRCT2/blob/master/io.openrct2.OpenRCT2.yaml#L65

Tnx!

**Comment by ghisvail** [comment]
You are correct, I missed the default cmake build type. Thanks for letting
me know.

Le jeu. 4 févr. 2021 à 11:24, Patric Stout <notifications@github.com> a
écrit :
