### ISSUE TITLE
Please include the free OPL3 MIDI SoundFont in "/app/share/sounds/sf2"

### ISSUE THREAD

**Issue by mrjpaxton** [flathub/org.openttd.OpenTTD#39]
Hi, everyone,

I was hoping that the Flatpak version of OpenTTD could use this OPL3 sound font - https://github.com/Mindwerks/opl3-soundfont

The package name in Debian is `opl3-soundfont`. And it is released under a CC-BY-SA 4.0 license.

My reasoning is that it sounds a lot better than the standard FluidSynth GM and GS SoundFonts that come with it. There are volume mixing issues with some instruments when using it. And in general, certain parts of the songs when played with the Jukebox sound terrible with the FluidSynth backend, and are often too loud.

I understand that vanilla OpenTTD heavily relies on Timidity+Freepats instead, but I thought a good alternative would be great.

I have also looked at these threads below, so I will reference them:
- https://github.com/OpenTTD/OpenTTD/issues/6873
- https://github.com/OpenTTD/OpenTTD/pull/7522

When I use `flatpak run org.openttd.OpenTTD -m fluidsynth:soundfont=/app/share/sounds/sf2/FluidR3_GM.sf2`, it works just fine.

However, when I try to run `flatpak run org.openttd.OpenTTD -m fluidsynth:soundfont=/usr/share/sounds/sf2/OPL-3_FM_128M.sf2` it returns this error:

```
fluidsynth: error: fluid_sfloader_load(): Failed to open '/usr/share/sounds/sf2/OPL-3_FM_128M.sf2': File does not exist.
fluidsynth: error: Unable to open file '/usr/share/sounds/sf2/OPL-3_FM_128M.sf2'
fluidsynth: error: Failed to load SoundFont "/usr/share/sounds/sf2/OPL-3_FM_128M.sf2"
Error: Unable to load driver 'fluidsynth'. The error was: Could not open sound font
```

Even when specifying `--filesystem=host` or `--filesystem=/usr/share/sounds/sf2/`, it will still return the exact same error. So for some reason, it won't load.

I even did some research to find out that the mysterious `/app/share/` directory actually points to `/var/lib/flatpak/app/org.openttd.OpenTTD/x86_64/stable/<HASH>/files/share/`, where <HASH> appears to be some sort of checksum, likely SHA-256.

Anyway, when I copied over the `/usr/share/sounds/sf2/OPL-3_FM_128M.sf2` (OPL-3 SoundFont) file to that `/var/lib/flatpak/<...>/share/sounds/sf2/` directory, it still refused to load it at all.

If there is any way anybody knows how to make that work, or can provide a fix for it, please let me know!

The version I am using is OpenTTD 1.10.3 (Flatpak stable repo).

**Comment by ghisvail** [comment]
@mrjpaxton I am open to the idea of using an alternative sound font.

Feel free to test it in a PR against the `beta` branch to target the upcoming release. CI should trigger a build and provide a version for anyone to try out.

**Comment by ghisvail** [comment]
Looks like version 1 is available straight from Github [releases](https://github.com/Mindwerks/opl3-soundfont/releases/download/1.0/OPL-3_FM_128M.sf2), with checksums in the README.

**Comment by mrjpaxton** [comment]
Honestly, I thought we would use the host's filesystem outside of the Sandbox, or specifically just the `/usr/share/sounds/sf2` folder.

However, I realized a problem with this... It can be a completely different directory depending on the operating system or distro.

I'm not too experienced building anything with Flatpak, so maybe someone else can try it. I imagine it should work fine. If not, then perhaps `extmidi` can be used instead of the `fluidsynth` plugin.

My biggest problem with `extmidi` is that it does not play well with the game's Jukebox controls. You can't pause, skip, etc...

**Comment by ghisvail** [comment]
@mrjpaxton Could you have a look at #40 and try the link in there with the test version? Let me know how it goes.

**Comment by ghisvail** [comment]
I have also tried an [alternative](https://github.com/flathub/org.openttd.OpenTTD/pull/44) with the [MuseScore_General](https://musescore.org/fr/manuel/soundfonts-et-fichiers-sfz) soundfont.

Although ymmv, I agree music tunes sound much better with both of these soudfonts. The `MuseScore_General` one also benefits from a significant reduction in size thanks to compression. If I were to pick one, it would likely be the latter.

Feel free to try both out (#40 and #44) and tell me what do you think @mrjpaxton

**Comment by ghisvail** [comment]
That being said, OPL-3 might sound closer to how tunes sounded back when the original TTD was developed.

**Comment by ghisvail** [comment]
I have submitted a [patch](https://github.com/OpenTTD/OpenTTD/pull/8953) upstream to support more means of overriding the soudfont used for OpenTTD. Meanwhile, I have also upgraded the default soundfont provided in the Flatpak to `FluidR3mono_GM`, replacing the regular `FluidR3` which indeed suffers from the limitation you highlighted.

**Comment by ghisvail** [comment]
Closing since an alternative to the Fluid soundfonts is now in use and sound quality noticeably improved as a result.
