### ISSUE TITLE
Wayland resolution and font problems

### ISSUE THREAD

**Issue by SuborbitalPigeon** [flathub/org.openttd.OpenTTD#70]
I have a 4k screen, and so have set my scaling factor to 2x in the GNOME settings. Running OpenTTD and using Wayland, it is not possible to set its resolution to 3840×2160 in the game, as the window goes off the screen edge.

A separate issue is when I try and set a custom font through openttd.cfg, the game crashes. Looking at the log, this happens in [InitFreeType](https://github.com/OpenTTD/OpenTTD/blob/release/12/src/fontcache.cpp#L681).

Disabling Wayland using flatseal allows both the full resolution to be set, and doesn't crash with custom font settings.

**Comment by ghisvail** [comment]
> Looking at the log

Best would be to open a separate issue for the font problem and provide the logs.

**Comment by SuborbitalPigeon** [comment]
That's fair, just found it odd that only happens under Wayland, which is why I mentioned it here.

**Comment by comick** [comment]
I have the same issue when custom font is set using Wayland. No issue starting the game from Xorg session.

**Comment by ghisvail** [comment]
> Disabling Wayland using flatseal allows both the full resolution to be set, and doesn't crash with custom font settings.

Marked as the solution to this issue.

**Comment by SuborbitalPigeon** [comment]
When installing OpenTTD on another computer and setting fonts, I discovered it also crashes. It turns out if I run `fc-cache` on the host before running OpenTTD, it works. See https://github.com/OpenTTD/OpenTTD/issues/10232.
