### ISSUE TITLE
Adding JGR's Patchpack

### ISSUE THREAD

**Issue by cthu1hoo** [flathub/org.openttd.OpenTTD#76]
I apologize if that is offtopic. 

I wonder, if there's any interest in adding JGRPP version of OpenTTD? I've done the actual packaging[1], based on this repo with some minor changes, but I have no clue how to fix metadata properly, what is really required, and is there really any point in bothering in the first place. 

Thanks in advance for any answers.

1. https://github.com/cthu1hoo/org.openttd.OpenTTD.jgrpp

**Comment by ghisvail** [comment]
I wonder why these patches are maintained separately instead of being submitted upstream, actually.

**Comment by cthu1hoo** [comment]
I dunno. All I know is that there's cool stuff (like cargodist, working schedules and vehicle spreading, etc.) which makes it almost a whole different game.

**Comment by ghisvail** [comment]
> which makes it almost a whole different game.

Which means re-using the OpenTTD branding _may_ be misleading.

I'd suggest the following:

- get in touch with upstream OpenTTD to check whether they are fine with it
- review the patches to check for malicious or unwanted alteration of the original code
- verify licensing compatibility between upstream OpenTTD (GPL) and the integrated patches
