### ISSUE TITLE
No in-game music after latest update

### ISSUE THREAD

**Issue by PatrickJosh** [flathub/org.openttd.OpenTTD#85]
Hello,

After the latest update of the Flatpak version via Flathub, I don't have in-game music any more. The sounds are still working, though.
When I start the game using the terminal, I get the following output:
[output.txt](https://github.com/flathub/org.openttd.OpenTTD/files/9593805/output.txt)

When I downgrade to commit `59ea6d37ff23dab91ae08c1a9e6370a46600c5ff04008c67af58b14a2c5450c0`, which is the second most recent version, the music works again. Terminal output also stays clean then.

Maybe is has to do with the upgrade of the runtime?

**Comment by ghisvail** [comment]
`fluidsynth: error: Failed to load SoundFont "/app/share/sounds/sf3/default-GM.sf3"`

Would explain why no music is played

**Comment by PatrickJosh** [comment]
Thanks for the quick respond. Is that an error on my side or does it have to do with the Flatpak?

**Comment by ghisvail** [comment]
I am having the same problem. Looks like a regression in `fluidsynth`.

**Comment by ghisvail** [comment]
Trying a test build with the previous runtime, just in case:

https://github.com/flathub/org.openttd.OpenTTD/pull/86

**Comment by ghisvail** [comment]
I reverted the runtime upgrade and music plays again. I need to investigate where the regression comes from before upgrading again.

**Comment by PatrickJosh** [comment]
Thank you a lot for the quick action. It works for me again with the new releases.
