### ISSUE TITLE
Disable Wayland support by default

### ISSUE THREAD

**Issue by Newbytee** [flathub/org.openttd.OpenTTD#93]
I'm a bit fan of Wayland, but unfortunately this game does not work well at all for me in SDL's Wayland mode. I cannot pan the screen properly. See the attached video below for a demonstration.

[openttd-problem.webm](https://user-images.githubusercontent.com/4428753/204048018-6064d50d-f5c4-4b53-b936-248d6f0b3a12.webm)

It's possible that this issue is GNOME-specific. I've not tested any other compositors. But, I would still recommend disabling `--socket=fallback-x11` which would let SDL fall back to Xwayland as it does by default, but still let those who want to override this using an environment variable do so. You'd just have to remove this line:

https://github.com/flathub/org.openttd.OpenTTD/blob/4ff54c04fffebdb6dc321d1d7a27993b62fdcded/org.openttd.OpenTTD.yaml#L14

**Comment by ghisvail** [comment]
Your fix did not work so I ended up using the standard X11 permission exclusively to fix this issue.

**Comment by Newbytee** [comment]
Weird, it worked fine for me locally. Thanks for fixing it anyway.

**Comment by Newbytee** [comment]
Oh, I see why my proposed fix didn't work. You'd also have had to add a line that enables the X11 socket as well. I didn't realise that wasn't enabled.

**Comment by ghisvail** [comment]
I'd rather have a different issue be opened which links to that one.

As far as the OP is concerned, their problem is fixed by disabling Wayland.

Yours could be titled "Investigate switching back to Wayland as default" for instance.
