### ISSUE TITLE
Research why native Wayland bugs out

### ISSUE THREAD

**Issue by orowith2os** [flathub/org.openttd.OpenTTD#97]
Coming from https://github.com/flathub/org.openttd.OpenTTD/issues/93

It needs to be tested once again on non-NVIDIA hardware, and on at least three compositors: GNOME, KDE, and Sway.

If it turns out that this issue would be a better fit upstream, I'll move it there.

**Comment by PatrickJosh** [comment]
This is probably an upstream issue. Please have a look at https://github.com/OpenTTD/OpenTTD/pull/10141, especially at the comments.

**Comment by ghisvail** [comment]
Fixed by #102
